services:
  db:
    image: mysql:8.1
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - mysql_data_ai:/var/lib/mysql

volumes:
  mysql_data_ai:
    driver: local
